export enum ApiLabel {
  LOGIN = 'LOGIN',
  REFRESH = 'REFRESH',
  GET_CHANGE_REQUESTS = 'GET_CHANGE_REQUESTS',
  GET_CLARIFICATION_REQUESTS = 'GET_CLARIFICATION_REQUESTS',
  GET_DEPARTMENTS = 'GET_DEPARTMENTS',
  GET_DIPLOMA_SESSIONS = 'GET_DIPLOMA_SESSIONS',
  GET_FIELDS_OF_STUDY = 'GET_FIELDS_OF_STUDY',
  GET_RESERVATIONS = 'GET_RESERVATIONS',
  GET_RESERVATIONS_MEMBERS = 'GET_RESERVATIONS_MEMBERS',
  GET_TIMETABLES = 'GET_TIMETABLES',
  GET_USER = 'GET_USER',
  REJECT_CLARIFICATION_REQUESTS = 'REJECT_CLARIFICATION_REQUESTS'
}
