package pwr.diplomaproject.model.enum

enum class TopicStatus {
    WAITING,
    SUGGESTED_BY_STUDENT,
    REJECTED_BY_LECTURER,
    REJECTED_BY_COORDINATOR,
    ACCEPTED_BY_COORDINATOR,
    NEEDS_CORRECTION,
    REJECTED_BY_COMMISSION,
    ACCEPTED_BY_COMMISSION
}