import { ApiLabel } from '../app/core/models/api-route.model';
import { AppLanguage } from '../app/core/models/app-language.model';

export const baseEnvironment = {
  fakeApi: {
    enabled: false,
    delayTime: 1000
  },
  defaultLanguage: AppLanguage.POLISH,
  serverConfig: {
    authBase: '/auth',
    base: '/api',
    api: {
      [ApiLabel.LOGIN]: '/oauth/token',
      [ApiLabel.REFRESH]: 'TODO REFRESH',
      [ApiLabel.MODIFY_TIMETABLE]: 'TODO MODIFY_TIMETABLE',
      [ApiLabel.ACCEPT_THESIS_WITH_LECTURER]: 'TODO ACCEPT_THESIS_WITH_LECTURER',
      [ApiLabel.CORRECT_THESIS_WITH_LECTURER]: 'TODO CORRECT_THESIS_WITH_LECTURER',
      [ApiLabel.REJECT_THESIS_WITH_LECTURER]: 'TODO REJECT_THESIS_WITH_LECTURER',
      [ApiLabel.ABANDON_MEMBER_RESERVATION]: 'TODO ABANDON_MEMBER_RESERVATION',
      [ApiLabel.APPROVE_CLARIFICATION_REQUEST]: 'TODO APPROVE_CLARIFICATION_REQUEST',
      [ApiLabel.APPROVE_CHANGE_REQUEST]: 'TODO APPROVE_CHANGE_REQUEST',
      [ApiLabel.APPROVE_THESIS_WITH_COORDINATOR]: 'TODO APPROVE_THESIS_WITH_COORDINATOR',
      [ApiLabel.APPROVE_THESIS_WITH_COMMITTEE_MEMBER]: 'TODO APPROVE_THESIS_WITH_COMMITTEE_MEMBER',
      [ApiLabel.CONFIRM_MEMBER_RESERVATION]: 'TODO CONFIRM_MEMBER_RESERVATION',
      [ApiLabel.CONFIRM_PARTICIPATION_IN_RESERVATION]: 'TODO CONFIRM_PARTICIPATION_IN_RESERVATION',
      [ApiLabel.CREATE_CLARIFICATION_REQUEST]: 'TODO CREATE_CLARIFICATION_REQUEST',
      [ApiLabel.CREATE_CHANGE_REQUEST]: 'TODO CREATE_CHANGE_REQUEST',
      [ApiLabel.CREATE_THESIS]: 'TODO CREATE_THESIS',
      [ApiLabel.CREATE_RESERVATION]: 'TODO CREATE_RESERVATION',
      [ApiLabel.REJECT_RESERVATION]: 'TODO REJECT_RESERVATION',
      [ApiLabel.ACCEPT_RESERVATION]: 'TODO ACCEPT_RESERVATION',
      [ApiLabel.GET_CHANGE_REQUEST]: 'TODO GET_CHANGE_REQUEST',
      [ApiLabel.GET_CHANGE_REQUESTS]: 'TODO GET_CHANGE_REQUESTS',
      [ApiLabel.GET_CLARIFICATION_REQUEST]: 'TODO GET_CLARIFICATION_REQUEST',
      [ApiLabel.GET_CLARIFICATION_REQUESTS]: 'TODO GET_CLARIFICATION_REQUESTS',
      [ApiLabel.GET_DEPARTMENT]: 'TODO GET_DEPARTMENT',
      [ApiLabel.GET_DEPARTMENTS]: 'TODO GET_DEPARTMENTS',
      [ApiLabel.GET_DIPLOMA_SESSION]: 'TODO GET_DIPLOMA_SESSION',
      [ApiLabel.GET_DIPLOMA_SESSIONS]: 'TODO GET_DIPLOMA_SESSIONS',
      [ApiLabel.GET_EMPLOYEE]: 'TODO GET_EMPLOYEE',
      [ApiLabel.GET_EMPLOYEES]: 'TODO GET_EMPLOYEES',
      [ApiLabel.GET_FIELD_OF_STUDY]: 'TODO GET_FIELD_OF_STUDY',
      [ApiLabel.GET_FIELDS_OF_STUDY]: 'TODO GET_FIELDS_OF_STUDY',
      [ApiLabel.GET_RESERVATION]: 'TODO GET_RESERVATION',
      [ApiLabel.GET_RESERVATIONS]: 'TODO GET_RESERVATIONS',
      [ApiLabel.GET_RESERVATION_MEMBERS]: 'TODO GET_RESERVATION_MEMBERS',
      [ApiLabel.GET_STUDENT]: 'TODO GET_STUDENT',
      [ApiLabel.GET_STUDENTS]: 'TODO GET_STUDENTS',
      [ApiLabel.GET_THESES]: 'TODO GET_THESES',
      [ApiLabel.GET_THESIS]: 'TODO GET_THESIS',
      [ApiLabel.GET_TIMETABLE]: 'TODO GET_TIMETABLE',
      [ApiLabel.GET_TIMETABLES]: 'TODO GET_TIMETABLES',
      [ApiLabel.GET_USER]: 'TODO GET_USER',
      [ApiLabel.REJECT_CLARIFICATION_REQUEST]: 'TODO REJECT_CLARIFICATION_REQUEST',
      [ApiLabel.REJECT_CHANGE_REQUEST]: 'TODO REJECT_CHANGE_REQUEST',
      [ApiLabel.REJECT_THESIS_WITH_COORDINATOR]: '/coordinator/subject/reject',
      [ApiLabel.REJECT_THESIS_WITH_COMMITTEE_MEMBER]: '/commission/subject/reject',
      [ApiLabel.REQUEST_THESIS_CORRECTIONS]: '/coordinator/subject/comment'
    }
  }
};
