export enum TopicStatus {
  Waiting = 'WAITING',
  TO_CORRECT = "TO_CORRECT",
  PROPOSED_BY_STUDENT = 'PROPOSED_BY_STUDENT',
  REJECTED_BY_LECTURER = 'REJECTED_BY_LECTURER',
  REJECTED_BY_COORDINATOR = 'REJECTED_BY_COORDINATOR',
  APPROVED_BY_COORDINATOR = 'APPROVED_BY_COORDINATOR',
  APPROVED_BY_COMMITTEE = 'APPROVED_BY_COMMITTEE',
}
