export enum ReservationStatus {
  WAITING = 'WAITING',
  SUBMITTED = "SUBMITTED",
  ACCEPTED = 'ACCEPTED',
  CONFIRMED = 'CONFIRMED',
  REJECTED_BY_LECTURER = 'REJECTED_BY_LECTURER',
  REJECTED_BY_STUDENT = 'REJECTED_BY_STUDENT',
}
